"""Structured output contracts for DAG execution.

Schema validation guarantees that routing values are syntactically
valid graph transitions.
"""

from typing import Literal

from pydantic import BaseModel, Field

class SubTask(BaseModel):
    id: str = Field(description="Unique ID for this subtask (e.g., 't1').")
    description: str = Field(description="Detailed instruction of what needs to be done.")
    required_capabilities: list[str] = Field(description="Tools required (e.g., 'Search', 'FileSystem', 'Python', 'Memory').")
    dependencies: list[str] = Field(description="List of task IDs that must complete before this runs.")

class ExecutionPlan(BaseModel):
    """The Planner's generated DAG of tasks."""
    tasks: list[SubTask] = Field(description="List of subtasks forming the execution DAG.")

class WorkerResult(BaseModel):
    """The generic worker's structured output."""
    output: str = Field(description="The final output, finding, or code generated by the worker.")
    error: str | None = Field(default=None, description="Any error encountered during tool execution.")
